version: "3.9"
services:
  app:
    container_name: node-app
    restart: always
    build:
      dockerfile: Dockerfile
      context: .
      target: dev
    volumes:
      - .:/opt/app/api
    ports:
      - "80:8080"