apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue-sky-deploy
  labels:
    app: blue-sky
spec:
  replicas: 3
  selector:
    matchLabels:
      app: blue-sky
  template:
    metadata:
      labels:
        app: blue-sky
    spec:
      containers:
        - name: blue-sky
          image: ""  # docker image
          ports:
            - containerPort: 80